env: MultiAgentMetaDrive

env_args:  
  num_agents: 10
  delay_done: 5
  allow_respawn: False

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
seed: 123
